In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4], [4, 4, 5, 6]])
a.ndim, a.shape

b = np.arange(9).reshape(3, 3)
b


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
import numpy as np

a = np.zeros((3, 4))
a

b = np.random.randint(0, 10, (2, 3))
b


array([[3, 5, 5],
       [3, 3, 7]])

In [ ]:
import numpy as np

a = np.zeros((3, 4))
a


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4], [4, 4, 5, 6]])
a.ndim, a.shape


(2, (2, 4))

In [ ]:
c = np.array ([[3,4,5,6],[4,5,6,8]])
c

array([[3, 4, 5, 6],
       [4, 5, 6, 8]])

In [ ]:
d = np.array([[5,6,7,8],[3,4,5,6]])
d

array([[5, 6, 7, 8],
       [3, 4, 5, 6]])

In [ ]:
e = np.concatenate((c,d),axis=1)
e

array([[3, 4, 5, 6, 5, 6, 7, 8],
       [4, 5, 6, 8, 3, 4, 5, 6]])

In [ ]:
F = np.hstack((c,d))
F

array([[3, 4, 5, 6, 5, 6, 7, 8],
       [4, 5, 6, 8, 3, 4, 5, 6]])

In [ ]:
F = np.vstack((c,d))
F

array([[3, 4, 5, 6],
       [4, 5, 6, 8],
       [5, 6, 7, 8],
       [3, 4, 5, 6]])

worksheet1


In [ ]:
#worksheet
#Initialize an empty array with size 2X2.
import numpy as np

empty_array = np.empty((2, 2))
empty_array


array([[4.70180122e-310, 0.00000000e+000],
       [4.70066679e-310, 6.86518525e-310]])

In [ ]:
#Initialize an all one array with size 4X2.
ones_array = np.ones((4, 2))
ones_array


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#Return a new array of given shape and type, filled with fill value.{Hint: np.full}
shape = (3, 3)
fill_value = 7
full_array = np.full(shape, fill_value)
full_array


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
#Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
zeros_like_array


array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
ones_like_array = np.ones_like(given_array)
ones_like_array


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
numpy_array


problem 2

In [ ]:
#Problem 2
#Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np

array_10_to_49 = np.arange(10, 50)
array_10_to_49


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
#2. Create a 3X3 matrix with values ranging from 0 to 8.
#{Hint:look for np.reshape()}
import numpy as np


array_0_to_8 = np.arange(9)

# Reshape the array into a 3x3 matrix
matrix_3x3 = array_0_to_8.reshape(3, 3)
matrix_3x3


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#Create a 3X3 identity matrix.{Hint:np.eye()}
import numpy as np

identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#Create a random array of size 30 and find the mean of the array.
#{Hint:check for np.random.random() and array.mean() function}
import numpy as np
random_array = np.random.random(30)
array_mean = random_array.mean()
array_mean

0.5648340480813752

In [13]:
#Create a 10X10 array with random values and find the minimum and maximum values.
import numpy as np

random_array = np.random.random((10, 10))
min_value = random_array.min()
max_value = random_array.max()
min_value, max_value

(0.0026721466467719557, 0.9985077756506082)

In [14]:
#Create a zero array of size 10 and replace 5th element with 1.
import numpy as np

zero_array = np.zeros(10)
zero_array[4] = 1
zero_array


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
#Reverse an array arr = [1,2,0,0,4,0].
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
reversed_arr


array([0, 4, 0, 0, 2, 1])

In [ ]:
#create a 2d array with 1 on border 0 inside
import numpy as np

border_array = np.ones((3,3))
border_array[1:-1, 1:-1] =0
border_array

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [ ]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np

checkerboard_matrix = np.zeros((8,8))
checkerboard_matrix[1::2,::2] = 1
checkerboard_matrix[::2,1::2] = 1
checkerboard_matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Problem 3

In [16]:
# problem 3
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
subtract_xy = x - y
print("Subtraction of x and y:\n", subtract_xy)

# 3. Multiply the arrays with any integer
multiply_x = x * 2  # Example with integer 2
print("Multiplication of x with 2:\n", multiply_x)

# 4. Find the square of each element of the array
square_x = np.square(x)
print("Square of each element in x:\n", square_x)

# 5. Find the dot product between: v and w ; x and v ; x and y
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product of x and v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenate x and y along row and Concatenate v and w along column
concatenate_xy = np.concatenate((x, y), axis=0)  # along row
print("Concatenate x and y along row:\n", concatenate_xy)

concatenate_vw = np.stack((v, w), axis=1)  # along column
print("Concatenate v and w along column:\n", concatenate_vw)

# 7. Concatenate x and v; observe and explain any errors
try:
    concatenate_xv = np.concatenate((x, v), axis=0)  # this will raise an error
    print("Concatenate x and v:\n", concatenate_xv)
except ValueError as e:
    print("Error:", e)
    print("Explanation: Arrays x and v cannot be concatenated along axis 0 because their dimensions do not match. x has shape (2, 2) while v has shape (2,). To concatenate along axis 0, they must have the same number of columns.")


Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Multiplication of x with 2:
 [[ 2  4]
 [ 6 10]]
Square of each element in x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Arrays x and v cannot be concatenated along axis 0 because their dimensions do not match. x has shape (2, 2) while v has shape (2,). To concatenate along axis 0, they must have the same number of columns.


#problem 4

In [17]:
#problem 4

import numpy as np

# Define arrays A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A.A⁻¹:\n", I)  # Should be close to the identity matrix

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB ≠ BA:", not np.array_equal(AB, BA))  # Compare if they are equal

# 3. Prove (AB)ᵀ = BᵀAᵀ
AB_transpose = np.transpose(AB)
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
BT_AT = np.dot(B_transpose, A_transpose)
print("\n(AB)ᵀ:\n", AB_transpose)
print("\nBᵀAᵀ:\n", BT_AT)
print("\n(AB)ᵀ = BᵀAᵀ:", np.array_equal(AB_transpose, BT_AT))


# Solve the system of linear equations using inverse method
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)
print("\nSolution using inverse method:\n", X)

# Solve using np.linalg.solve
X = np.linalg.solve(A,B)
print("\nSolution using np.linalg.solve:\n", X)

A.A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB ≠ BA: True

(AB)ᵀ:
 [[23 51]
 [13 29]]

BᵀAᵀ:
 [[23 51]
 [13 29]]

(AB)ᵀ = BᵀAᵀ: True

Solution using inverse method:
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]


#problem 5

In [18]:
# problem5
import numpy as np
import time

# Step 1: Element-wise Addition

# Using Python Lists
list1 = list(range(1000000))
list2 = list(range(1000000))

start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
print(f"Time taken for element-wise addition using Python lists: {end_time - start_time:.5f} seconds")

# Using NumPy Arrays
array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
array_sum = array1 + array2
end_time = time.time()
print(f"Time taken for element-wise addition using NumPy arrays: {end_time - start_time:.5f} seconds")

# Step 2: Element-wise Multiplication

# Using Python Lists
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time:.5f} seconds")

# Using NumPy Arrays
start_time = time.time()
array_product = array1 * array2
end_time = time.time()
print(f"Time taken for element-wise multiplication using NumPy arrays: {end_time - start_time:.5f} seconds")

# Step 3: Dot Product

# Using Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()
print(f"Time taken for dot product using Python lists: {end_time - start_time:.5f} seconds")

# Using NumPy Arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print(f"Time taken for dot product using NumPy arrays: {end_time - start_time:.5f} seconds")

# Step 4: Matrix Multiplication

# Using Python Lists
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]

def matrix_multiply(A, B):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][j] * B[j][k]
    return result

start_time = time.time()
result_matrix = matrix_multiply(matrix1, matrix2)
end_time = time.time()
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time:.5f} seconds")

# Using NumPy Arrays
matrix1_np = np.arange(1000000).reshape(1000, 1000)
matrix2_np = np.arange(1000000).reshape(1000, 1000)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken for matrix multiplication using NumPy arrays: {end_time - start_time:.5f} seconds")


Time taken for element-wise addition using Python lists: 0.17593 seconds
Time taken for element-wise addition using NumPy arrays: 0.00416 seconds
Time taken for element-wise multiplication using Python lists: 0.16620 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.00260 seconds
Time taken for dot product using Python lists: 0.15036 seconds
Time taken for dot product using NumPy arrays: 0.00196 seconds
Time taken for matrix multiplication using Python lists: 245.27594 seconds
Time taken for matrix multiplication using NumPy arrays: 4.31916 seconds
